services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: finansync
      POSTGRES_USER: finansync_user
      POSTGRES_PASSWORD: secure_password
      PGUSER: finansync_user  # This ensures the user is created
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
